id: 155243f4-d962-4717-8a7b-b15b6d112660
name: McAfee ePO - Deployment failed
description: |
  'Detects when errors occur during deployment new changes/policies.'
severity: High
requiredDataConnectors:
  - connectorId: McAfeeePO
    dataTypes:
      - Syslog
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - DefenseEvasion
relevantTechniques:
  - T1562
query: |
  McAfeeEPOEvent
  | where EventId == '2412'
  | extend IPCustomEntity = DvcIpAddr, HostCustomEntity = DvcHostname
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
  - entityType: Host
    fieldMappings:
      - identifier: FullName
        columnName: HostCustomEntity
