id: 7cbd46ce-5121-11ec-bf63-0242ac130002
name: PaloAlto - Incomplete application protocol
description: |
  'Query shows incomplete application protocol'
severity: Medium
requiredDataConnectors:
  - connectorId: PaloAltoCDL
    dataTypes:
      - PaloAltoCDLEvent
tactics:
  - InitialAccess
relevantTechniques:
  - T1190
  - T1133
query: |
  PaloAltoCDLEvent
  | where TimeGenerated > ago(24h)
  | where NetworkApplicationProtocol has_any ("incomplete", "Not-Applicable", "insufficient")
  | extend UrlCustomEntity = Url, IPCustomEntity = DstIpAddr
entityMappings:
  - entityType: URL
    fieldMappings:
      - identifier: Url
        columnName: UrlCustomEntity
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
