id: 0a18756a-5123-11ec-bf63-0242ac130002
name: PaloAlto - Rare application layer protocols
description: |
  'Query shows Rare application layer protocols'
severity: Low
requiredDataConnectors:
  - connectorId: PaloAltoCDL
    dataTypes:
      - PaloAltoCDLEvent
tactics:
  - InitialAccess
relevantTechniques:
  - T1190
  - T1133
query: |
  PaloAltoCDLEvent
  | where TimeGenerated > ago(24h)
  | where isnotempty(NetworkApplicationProtocol) 
  | summarize ApplicationLayerProtocol = count() by NetworkApplicationProtocol
  | top 10 by ApplicationLayerProtocol asc
  | extend UrlCustomEntity = NetworkApplicationProtocol
entityMappings:
  - entityType: URL
    fieldMappings:
      - identifier: Url
        columnName: UrlCustomEntity
