id: 6e4b6758-23a5-409b-a444-9bdef78e9dcc
name: PaloAlto - Outdated config vesions
description: |
  'Query shows outdated config vesions'
severity: Medium
requiredDataConnectors:
  - connectorId: PaloAltoCDL
    dataTypes:
      - PaloAltoCDLEvent
  - connectorId: PaloAltoCDLAma
    dataTypes:
      - PaloAltoCDLEvent
tactics:
  - InitialAccess
relevantTechniques:
  - T1190
  - T1133
query: |
  let cur_ver = dynamic(['0.1']); //put latest config version here
  PaloAltoCDLEvent
  | where TimeGenerated > ago(24h)
  | where isnotempty(PanOSConfigVersion)
  | where PanOSConfigVersion != cur_ver
  | project SrcIpAddr, PanOSConfigVersion
  | extend IPCustomEntity = SrcIpAddr
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
        