id: 637697be-2fc5-4c57-a7b0-ac79d181a7ab
name: Cross-tenant Access Settings Organization Inbound Direct Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationInboundDirectSettingsChanged.yaml'
version: 1.0.2
kind: Scheduled
