id: 0b130033-bd5a-48c4-b606-84a8614ff3c0
name: Mail.Read Permissions Granted to Application
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/MailPermissionsAddedToApplication.yaml'
version: 1.0.1