id: c2b123c3-e909-4c2e-bd4a-92b7055cf7e0
name: DMARC Not Configured
description: |
  'DMARC Not Configured'
severity: Medium
status: Available
requiredDataConnectors:
  - connectorId: HVPollingIDAzureFunctions
    dataTypes:
      - HackerViewLog_Azure_1_CL
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
- Collection
relevantTechniques:
- T1114
query: |+
  HackerViewLog_Azure_1_CL | where severity_s == "medium" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "DMARC Not Configured"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: 5h
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
  aggregationKind: SingleAlert
entityMappings:
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: meta_resolved_ip_s
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: meta_host_s
- entityType: URL
  fieldMappings:
  - identifier: Url
    columnName: hackerview_link_s
suppressionDuration: 5h
version: 1.0.0
kind: Scheduled