id: c2b123c3-e909-4c2e-bd4a-92b7055cf7e0
name: DMARC Not Configured
description: |
  'DMARC Not Configured'
severity: Medium
status: Available
requiredDataConnectors:
- connectorId: CTM360HackerViewConnectorDefinition
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Collection
relevantTechniques:
  - T1114
query: |+
  HackerViewLog | where Severity == "medium" | where Status == "New" | where Status != "inactive"  | where Title == "DMARC Not Configured"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
entityMappings:
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: MetaResolvedIp
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: MetaHost
- entityType: URL
  fieldMappings:
  - identifier: Url
    columnName: HackerViewLink
suppressionDuration: 5h
version: 1.0.5
kind: Scheduled





