id: 833b5430-9454-41f8-96ac-bf77e67df53b
name: Exposed Misconfiguration (Informational)
description: New Exposed Misconfiguration with severity Informational found
severity: Informational
status: Available
requiredDataConnectors:
- connectorId: CTM360CBSConnectorDefinition
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
- ResourceDevelopment
relevantTechniques:
- T1587
query: CBSLog | where Severity == "Informational" | where IncidentType == "Exposed
  Misconfiguration" | where Status != "Closed" or Status != "Resolved"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
suppressionDuration: 5h
version: 1.0.1
kind: Scheduled




