id: 71ce7988-130e-42d6-82ea-a687c13011b2
name: Exposed Misconfiguration (High)
description: New Exposed Misconfiguration with severity High found
severity: High
status: Available
requiredDataConnectors:
- connectorId: CTM360CBSConnectorDefinition
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
- ResourceDevelopment
relevantTechniques:
- T1587
query: CBSLog | where Severity == "High" | where IncidentType == "Exposed Misconfiguration"
  | where Status != "Closed" or Status != "Resolved"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
suppressionDuration: 5h
version: 1.0.1
kind: Scheduled




