id: 6e343c15-d718-435c-a64d-37f4a408c7c2
name: Exposed Misconfiguration (Medium)
description: New Exposed Misconfiguration with severity Medium found
severity: Medium
status: Available
requiredDataConnectors:
- connectorId: CTM360CBSConnectorDefinition
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
- ResourceDevelopment
relevantTechniques:
- T1587
query: CBSLog | where Severity == "Medium" | where IncidentType == "Exposed
  Misconfiguration" | where Status != "Closed" or Status != "Resolved"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
suppressionDuration: 5h
version: 1.0.1
kind: Scheduled




