id: ba25d152-3741-4564-b9dd-1f0afe7829ff
name: Exposed Misconfiguration (Low)
description: New Exposed Misconfiguration with severity Low found
severity: Low
status: Available
requiredDataConnectors:
- connectorId: CTM360CBSConnectorDefinition
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
tactics:
- ResourceDevelopment
relevantTechniques:
- T1587
query: CBSLog | where Severity == "Low" | where IncidentType == "Exposed Misconfiguration"
  | where Status != "Closed" or Status != "Resolved"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
suppressionDuration: 5h
version: 1.0.1
kind: Scheduled




