id: f78c03ec-4397-42f6-9c51-a54421817fd8
name: SPF Not Configured
description: |
  'SPF Not Configured'
severity: Low
status: Available
requiredDataConnectors:
  - connectorId: HVPollingIDAzureFunctions
    dataTypes:
      - HackerViewLog_Azure_1_CL
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
query: HackerViewLog_Azure_1_CL | where severity_s == "low" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "SPF Not Configured"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
  aggregationKind: SingleAlert
entityMappings:
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: meta_resolved_ip_s
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: meta_host_s
- entityType: URL
  fieldMappings:
  - identifier: Url
    columnName: hackerview_link_s
suppressionDuration: 5h
version: 1.0.1
kind: Scheduled