id: f78c03ec-4397-42f6-9c51-a54421817fd8
name: SPF Not Configured
description: |
  'SPF Not Configured'
severity: Low
status: Available
requiredDataConnectors:
- connectorId: CTM360HackerViewConnectorDefinition
tactics:
  - InitialAccess
  - Discovery
relevantTechniques:
  - T1189
  - T1087
queryFrequency: 5m
queryPeriod: 5m
triggerOperator: gt
triggerThreshold: 0
query: HackerViewLog | where Severity == "low" | where Status == "New" | where Status != "inactive"  | where Title == "SPF Not Configured"
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
eventGroupingSettings:
  aggregationKind: SingleAlert
entityMappings:
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: MetaResolvedIp
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: MetaHost
- entityType: URL
  fieldMappings:
  - identifier: Url
    columnName: HackerViewLink
suppressionDuration: 5h
version: 1.0.5
kind: Scheduled





