id: 6d4d7689-5e1d-4687-b1fc-eb0b7340c9a3
name: Cisco WSA - Top aplications
description: |
  'Query searches for top applications.'
severity: Medium
requiredDataConnectors:
  - connectorId: CiscoWSA
    dataTypes:
      - CiscoWSAEvent
tactics:
  - InitialAccess
relevantTechniques:
  - T1189
query: |
  CiscoWSAEvent
  | where TimeGenerated > ago(24h)
  | summarize count() by AvcApplicationName, SrcUserName
  | extend AccountCustomEntity = SrcUserName
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
