id: 686ec2d3-fdbb-4fa2-b834-ff1d0f2486fb
name: Cisco WSA - Rare aplications
description: |
  'Query searches for rare applications.'
severity: Medium
requiredDataConnectors:
  - connectorId: CiscoWSA
    dataTypes:
      - CiscoWSAEvent
tactics:
  - CommandAndControl
  - Exfiltration
relevantTechniques:
  - T1048
  - T1567
query: |
  CiscoWSAEvent
  | where TimeGenerated > ago(24h)
  | summarize count() by AvcApplicationName, SrcUserName
  | order by count_ asc
  | extend AccountCustomEntity = SrcUserName
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
