id: f78e0bb9-2878-4e36-b9c9-6141bff8d3dd
name: Backup Repository Settings Updated
description: Detects when backup repository settings are updated in Veeam Backup &
  Replication. This might indicate configuration changes that require review.
severity: Low
status: Available
requiredDataConnectors:
- connectorId: Syslog
  dataTypes:
  - Syslog
- connectorId: SyslogAma
  dataTypes:
  - Syslog
queryFrequency: 3h
queryPeriod: 3h
triggerOperator: gt
triggerThreshold: 0
eventGroupingSettings:
  aggregationKind: AlertPerResult
tactics:
- DefenseEvasion
- Impact
relevantTechniques:
- T1562.001
- T1490
query: "Veeam_GetSecurityEvents\n| where instanceId == 28100\n| extend RepositoryName\
  \ =  extract(\"RepositoryName=\\\"(?<RepositoryName>[^\\\"]*)\\\"\", 1, SyslogMessage)\n\
  | project\n    Date = format_datetime(TimeGenerated, 'dd.MM.yyyy HH:mm'),\n    DataSource\
  \ = original_host,\n    EventId = instanceId,\n    [\"User Name\"] = user,\n   \
  \ [\"Object Name\"] = RepositoryName,\n    MessageDetails = Description,\n   Severity\
  \ = SeverityDescription"
version: 1.0.0
kind: Scheduled
customDetails:
  Date: Date
  VbrHostName: DataSource
  EventId: EventId
  MessageDetails: MessageDetails
  Severity: Severity
