id: e838519b-1f03-417f-863b-6c1a141677ee
name: McAfee ePO - Applications blocked or contained
description: |
  'Query searches for blocked or contained applications.'
requiredDataConnectors:
  - connectorId: McAfeeePO
    dataTypes:
      - Syslog
tactics:
  - InitialAccess
  - Execution
relevantTechniques:
  - T1204
  - T1189
query: |
  let lbtime = 24h;
  McAfeeEPOEvent
  | where TimeGenerated > ago(lbtime)
  | where EventId in ('18002', '37275')
  | extend Reason = case(EventId == '18002', "Application blocked",
                        "Application contained")
  | project DvcIpAddr, DstFileName
  | extend IPCustomEntity = DvcIpAddr
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity