id: ea0f2cc5-9ee4-45b0-bc19-fdbdf37b4db4
name: SAP - Security Audit Log Configuration Change
description: |
    Idenitifes changes for configuration in Securiy Audit Log

    Source Action: change any  Security Audit Log Configuration using SM19/RSAU_CONFIG. (Filters/Status/Recording mode etc..)

    *Data Sources: SAPcon -  Audit Log*
severity: Medium
requiredDataConnectors:
-   connectorId: SAP
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
- Persistence
- Exfiltration
- DefenseEvasion
relevantTechniques: ''
query: |
    // Audit Log Classes - Audit Log Configuration Events
    let AuditClasses = dynamic(['AUE','AUF','AUI','AUJ','FU0','E05']); // Relevant messages
    SAPAuditLog
    | where MessageID in (AuditClasses)
    | project
    // Details
    TimeGenerated, Instance, SystemID, User, MessageText,
    Email, TerminalIPv6, Host
alertDetailsOverride: null
customDetails:
    SAP_User: User
entityMappings:
-   entityType: IP
    fieldMappings:
    -   identifier: Address
        columnName: TerminalIPv6
-   entityType: Account
    fieldMappings:
    -   identifier: FullName
        columnName: Email
-   entityType: Host
    fieldMappings:
    -   identifier: FullName
        columnName: Host
-   entityType: CloudApplication
    fieldMappings:
    -   identifier: Name
        columnName: SystemID
    -   identifier: InstanceName
        columnName: Instance
eventGroupingSettings:
    aggregationKind: SingleAlert
kind: Scheduled
version: 2.0.19
