id: 78fbdc7d-6136-4afc-9cc5-5e5aff1563ae
name: SAP - Insecure FTP servers configuration
description: |4
     Identifies Insecure FTP servers configuration - FTP Whitelist is empty / Contains Placeholders.

    Source Action: Do not maintain / maintain values which contains placeholders in table SAPFTP_SERVERS using maintenance view SAPFTP_SERVERS_V. (SM30)

    *Data Sources: SAPcon -  Audit Log*
severity: Medium
requiredDataConnectors:
-   connectorId: SAP
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
- InitialAccess
- CommandAndControl
relevantTechniques: ''
query: |
    // Define variables
    let AuditClasses = dynamic(['DU1', 'DU2']); // Messages of FTP Whitelist is empty / Contains Placeholders
    // Query logic
    SAPAuditLog
    | where MessageID in (AuditClasses)
    | project TimeGenerated, Instance, SystemID, ClientID, User, Email, TerminalIPv6, Host, Reason = MessageText
alertDetailsOverride: null
customDetails:
    SAP_User: User
entityMappings:
-   entityType: Account
    fieldMappings:
    -   identifier: FullName
        columnName: Email
-   entityType: IP
    fieldMappings:
    -   identifier: Address
        columnName: TerminalIPv6
-   entityType: Host
    fieldMappings:
    -   identifier: FullName
        columnName: Host
-   entityType: CloudApplication
    fieldMappings:
    -   identifier: Name
        columnName: SystemID
    -   identifier: AppId
        columnName: ClientID
    -   identifier: InstanceName
        columnName: Instance
eventGroupingSettings:
    aggregationKind: SingleAlert
kind: Scheduled
version: 2.0.19
