id: fa748dc3-00ee-41cb-b54e-8acd56041b2a
Function:
  Title: Parser for ExchangeEnvironmentList
  Version: '1.0.1'
  LastUpdated: '2023-09-13'
Category: Microsoft Sentinel Parser
FunctionName: ExchangeEnvironmentList
FunctionAlias: ExchangeEnvironmentList
FunctionParams:
  - Name: Target
    Type: string
    Description: The target environment to query. Valid values are "On-Premises" or "Online". Default is "On-Premises".
    DefaultValue: 'On-Premises'
FunctionQuery: |
    // Parameters simulation
    // If you need to test the parser execution without saving it as a function, uncomment the bellow variable to simulate parameters values.
    //
    // let Target = 'On-Premises';
    //
    // Parameters definition
    let _target = iff(isnull(Target) or isempty(Target),"On-Premises",Target);
    let ScalarbaseRequest = union isfuzzy=true withsource=TableName ESIAPIExchange*,ESIExchange*
        | extend Source = iff (TableName contains "Online", "Online", "On-Premises")
        | where _target == 'All' or Source == _target;
    // Base Request
    ScalarbaseRequest | summarize by ESIEnvironment_s | project-rename ESIEnvironment = ESIEnvironment_s