id: 6ae7b9e0-462a-11ec-81d3-0242ac130003
name: Zscaler - Applications using by accounts
description: |
  'Query shows applications using by accounts.'
severity: Low
requiredDataConnectors:
  - connectorId: ZscalerPrivateAccess
    dataTypes:
      - ZPAEvent
tactics:
  - InitialAccess
relevantTechniques:
  - T1190
  - T1133
query: |
  ZPAEvent
  | where isnotempty(Application)
  | summarize Users = make_set(DstUserName) by Application
  | extend AccountCustomEntity = Users
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: AccountCustomEntity
