jobs:
- job: "DataConnectorValidations"
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
      command: 'install'
  - script: 'npm run tsc && node .script/dataConnectorValidator.js'
    displayName: 'Data Connector Validations'
