jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: AzureKeyVault@2
      inputs:
        keyVaultName: 'keyvaultforcatgithub'
        secretsFilter: '*'
        ConnectedServiceName: 'eco-connector-test-service-connection'
        runAsPreJob: true
    - script: |
        # Set environment variables using the values fetched from Azure Key Vault
        GITHUBAPPID=$(GITHUBAPPID) GITHUBAPPINSTALLATIONID=$(GITHUBAPPINSTALLATIONID) GITHUBAPPPRIVATEKEY=$(GITHUBAPPPRIVATEKEY)
      displayName: 'Print and Set Environment Variables'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      env:
        GITHUBAPPID: $(GITHUBAPPID)
        GITHUBAPPINSTALLATIONID: $(GITHUBAPPINSTALLATIONID)
        GITHUBAPPPRIVATEKEY: $(GITHUBAPPPRIVATEKEY)
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
