jobs:
- job: "precommitValidation"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        pip3 install pre-commit
      displayName: 'Install requirements'
    - script: |
        pre-commit run --all-files --show-diff-on-failure
        exit $RET
      displayName: 'Pre-commit check - server side'
