jobs:
  - job: "sampleDataValidator"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: Npm@1
        displayName: "npm install"
        inputs:
          verbose: false
          command: "install"
      - script: "npm install -g npm@6.14.15 && npm run tsc && node .script/sampleDataValidator.js"
        displayName: "sample Data Validator"
