jobs:
  - job: "sampleDataValidator"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: Npm@1
        displayName: "npm install"
        inputs:
          verbose: false
          command: "install"
      - script: "npm run tsc && node .script/sampleDataValidator.js"
        displayName: "sample Data Validator"
