jobs:
- job: "WorkbooksTemplateValidations"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: 'npm install -g npm@6.14.15;which npm;npm -v'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
      command: 'install'
  - script: 'npm run tsc && node .script/workbooksTemplateValidator.js'
    displayName: 'Workbooks Template Validations'
