jobs:
- job: "WorkbooksValidations"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
      command: 'install'
  - script: 'npm run tsc && node .script/workbooksMetadataValidator.js'
    displayName: 'Workbooks Metadata Validations'
