id: 359ddb25-eab1-4ef5-8303-ed3a9b680690
name: Cyble Vision Alerts Cyble Web Applications
description: |
  'Creates an incident for each discovered or exposed web application detected by Cyble Intelligence. Useful for SOC teams to investigate externally facing login portals, misconfigurations, and exposed infrastructure.'
severity: Low
status: Available
requiredDataConnectors:
- connectorId: CybleVisionAlerts
  dataTypes:
  - CybleVisionAlerts_CL
enabled: true
queryFrequency: 30m
queryPeriod: 30m
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT5M
eventGroupingSettings:
  aggregationKind: AlertPerResult
tactics:
- Reconnaissance
relevantTechniques:
- T1595
- T1592
query: |
  Alerts_web_applications
  | where Service == "web_applications"
  | extend MappedSeverity = Severity
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: PT5H
    matchingMethod: AllEntities
alertDetailsOverride:
  alertDisplayNameFormat: Cyble Web Application Found  {{WA_Title_Nested}}
  alertDescriptionFormat: |
    A web application was detected by Cyble Intelligence.
    Host {{WA_Host_Nested}}
    Port {{WA_Port_Nested}}
    URL {{WA_URL}}
customDetails:
  MappedSeverity: Severity
  Status: Status
  AlertID: AlertID
  Service: Service
  Host: WA_Host_Nested
  DetectedURL: WA_URL
  Title: WA_Title_Nested
entityMappings:
- entityType: URL
  fieldMappings:
  - identifier: Url
    columnName: WA_URL
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: IP
version: 1.0.0
kind: Scheduled
