name: Add Comment on Content PR On Merge

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  checkAutomatedPR:
    if: ${{ github.event.pull_request.merged && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/checkAutomatedPR.yaml

  getAuthorName:
    runs-on: ubuntu-latest
    needs: checkAutomatedPR
    if: ${{ needs.checkAutomatedPR.outputs.isAutomatedPR == 'False' && !github.event.pull_request.head.repo.fork }} 
    outputs:
      authorName: ${{ steps.step1.outputs.authorName }}
    steps:
      - shell: pwsh
        id: step1
        run: |
          $authorName = '${{ github.event.client_payload.github.actor }}'
          if ($authorName -eq '')
          {
            $authorName = "${{ github.event.pull_request.user.login }}"
          }
          Write-Output "authorName=$authorName" >> $env:GITHUB_OUTPUT
          Write-Host "Author Name is $authorName"
  
  solutionNameDetails:
    if: ${{ github.event.pull_request.merged && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/getSolutionName.yaml
    secrets: inherit
    
  addCommentOnContentPROnMerge:
    needs: [solutionNameDetails, getAuthorName, checkAutomatedPR]
    if: ${{ needs.solutionNameDetails.outputs.solutionName != '' && needs.checkAutomatedPR.outputs.isAutomatedPR == 'False' && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/addComment.yaml
    with:
      message: "@${{ needs.getAuthorName.outputs.authorName }} This pull request has been merged. If this should be followed by creating a new/updated solution package, please comment `/package` below to generate the solution package. Before you begin, please review the pre-requisites guidance for package generation [here](https://github.com/Azure/Azure-Sentinel/blob/master/README.md)"
