name: Get Solution Name

on:
  workflow_call:
    outputs:
      solutionName:
        description: "Solution name for the current pr"
        value: ${{ jobs.currentPRSolutionName.outputs.sName }}

env:
  BRANCH_NAME: "${{ github.event.client_payload.pull_request.head.ref }}"

jobs:
  currentPRSolutionName:
    name: Generate output - Solution Name
    runs-on: ubuntu-latest
    outputs:
      sName: ${{ steps.getSolutionName.outputs.solutionName }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0
          ref: "${{ env.BRANCH_NAME }}"
      - name: Identify Solution
        shell: pwsh
        id: getSolutionName
        run: |
          $instrumentationKey = "${{ vars.APPINSIGHTS }}"
          $runId = "${{ github.run_id }}"
          $pullRequestNumber = "${{ github.event.client_payload.pullRequestNumber }}"
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/getSolutionName.ps1 $runId $pullRequestNumber $instrumentationKey
