name: Validate Hyperlinks in PR
env:
  BASE_FOLDER_PATH: "${{ vars.BASEFOLDERPATH }}"
  APPINSIGHTS: "${{ vars.APPINSIGHTS }}"
  GITHUB_APPS_ID: "${{ secrets.APPLICATION_ID }}"
  GITHUB_APPS_KEY: "${{ secrets.APPLICATION_PRIVATE_KEY }}"

on:
  pull_request:
    branches:
      - master
    paths:
      - Solutions/**

jobs:
  validate-pr-links:
    if: ${{ !github.event.pull_request.head.repo.fork && !contains(github.event.client_payload.pull_request.head.ref , 'dependabot/') && !contains(github.event.client_payload.pullRequestBranchName , 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9
        with:
          app-id: ${{ env.GITHUB_APPS_ID }}
          private-key: ${{ env.GITHUB_APPS_KEY }}

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        env:
          GeneratedToken: ${{ steps.generate_token.outputs.token }}
        with:
          fetch-depth: 0
          token: ${{ env.GeneratedToken }}
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        env:
          RUNID: "${{ github.run_id }}"
          PULL_REQUEST_NUMBER: "${{ github.event.client_payload.pull_request.number || github.event.client_payload.pullRequestNumber || github.event.pull_request.number }}"
        run: |
          $runId = "${{ env.RUNID }}"
          $instrumentationKey = "${{ env.APPINSIGHTS }}"
          $pullRequestNumber = "${{ env.PULL_REQUEST_NUMBER }}"
          $baseFolderPath = "${{ env.BASE_FOLDER_PATH }}" 
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/hyperlink-validation.ps1 $runId $pullRequestNumber $instrumentationKey $baseFolderPath