name: Scanning for secrets in commits
on:
 pull_request:
    branches:
      - master
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        sparse-checkout: |
          .github/
          .script/
        sparse-checkout-cone-mode: false
    - name: Checkout PR changes only
      run: |
        git fetch origin ${{ github.event.pull_request.base.sha }}
        git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.sha }} > changed_files.txt
        cat changed_files.txt
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
