name: Scanning for secrets in commits
on:
 pull_request:
    branches:
      - master
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 10
    - name: Remove archive files before running TruffleHog
      run: |
        find . -type f \( -name '*.zip' -o -name '*.tar' -o -name '*.gz' -o -name '*.rar' -o -name '*.7z' -o -name '*.tgz' -o -name '*.bz2' -o -name '*.xz' \) -delete
        echo "Removed archive files to prevent disk space issues"
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
