name: Deploy Content to sentinel-test [3f648323-24b3-43be-8993-94d310832b49]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-3f648323-24b3-43be-8993-94d310832b49.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ development ]
    paths:
    - 'Solutions/SonicWall Firewall/**'
    - 'Parsers/ASimNetworkSession/ARM/ASimNetworkSessionSonicWallFirewall/**' 
    - 'Parsers/ASimNetworkSession/ARM/vimNetworkSessionSonicWallFirewall/**'
    - 'Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionSonicWallFirewall.yaml'
    - 'Parsers/ASimNetworkSession/Parsers/vimNetworkSessionSonicWallFirewall.yaml'
    - 'Parsers/ASimNetworkSession/ASimNetworkSessionV1/ARM/ASimNetworkSessionSonicWallFirewall/**'
    - 'Parsers/ASimNetworkSession/ASimNetworkSessionV1/ProductParsers/NetworkSessionSonicWallFirewall.yaml'
    - 'Parsers/ASimWebSession/ARM/ASimWebSessionSonicWallFirewall/**'
    - 'Parsers/ASimWebSession/ARM/vimWebSessionSonicWallFirewall/**'
    - 'Parsers/ASimWebSession/Parsers/ASimWebSessionSonicWallFirewall.yaml'
    - '!.script/**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-3f648323-24b3-43be-8993-94d310832b49.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinel-test'
      workspaceName: 'sentinel-test'
      workspaceId: '51a31b89-1f30-4742-9528-9a24db4bb3c3'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_3f64832324b343be899394d310832b49 }}
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook'
      branch: 'development'
      sourceControlId: '3f648323-24b3-43be-8993-94d310832b49'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_3f64832324b343be899394d310832b49 }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_3f64832324b343be899394d310832b49 }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_3f64832324b343be899394d310832b49 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-3f648323-24b3-43be-8993-94d310832b49.ps1
